#!/usr/bin/env node
const fs = require("fs");
const path = require("path");

const ROOT_DIR = path.resolve(__dirname, "..");
const MAX_BLOG_LIMIT = 100;

const TOPIC_CATALOG = [
  {
    "id": "volvo-penta-d4-d6-d13",
    "file_tr": "blog-volvo-penta-d4-d6-d13-bakim-ve-arizalar.html",
    "file_en": "blog-volvo-penta-d4-d6-d13-maintenance-and-faults.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/volvo-penta-d4-d6-ozel-servis.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Volvo Penta D4, D6 ve D13 Bakım Rehberi ve Arıza Teşhisi | DM MARİN",
    "title_en": "Volvo Penta D4, D6 & D13 Marine Engine Maintenance & Diagnostics | DM MARIN",
    "h1_tr": "Volvo Penta D4, D6 ve D13 Bakım Rehberi ve Arıza Teşhisi",
    "h1_en": "Volvo Penta D4, D6 & D13 Marine Engine Maintenance & Diagnostics",
    "desc_tr": "Volvo Penta D4, D6 ve D13 Common Rail marin dizel motorlarda 100/200/500 saatlik periyodik bakım takvimi, kompresör yağı, aftercooler ve EVC arıza kodları rehberi.",
    "desc_en": "Scheduled maintenance guide for Volvo Penta D4, D6 and D13 Common Rail marine diesels: 100/200/500 hr service, compressor oil, aftercoolers, and EVC diagnostic codes.",
    "keywords_tr": "volvo penta d6 servis, volvo d4 bakım, volvo penta arıza kodları, d13 marin motor, volvo penta istanbul",
    "keywords_en": "volvo penta d6 service, volvo d4 maintenance, volvo penta diagnostics turkey, d13 marine diesel repair"
  },
  {
    "id": "volvo-ips-drive-maintenance",
    "file_tr": "blog-volvo-penta-ips-pod-surucu-bakimi.html",
    "file_en": "blog-volvo-penta-ips-pod-drive-maintenance-service.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/volvo-penta-d4-d6-ozel-servis.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Volvo Penta IPS Pod Sürücü Bakımı, Yağ Değişimi ve Keçe Kontrolü | DM MARİN",
    "title_en": "Volvo Penta IPS Pod Drive Maintenance, Oil & Seal Service | DM MARIN",
    "h1_tr": "Volvo Penta IPS Pod Sürücü Bakımı ve Sezonluk Kontroller",
    "h1_en": "Volvo Penta IPS Pod Drive Maintenance & Scheduled Service",
    "desc_tr": "Volvo Penta IPS 500, 600, 800, 950, 1050 ve 1200 pod sürücülerde şanzıman sentetik yağ değişimi, pervane şaftı çift keçe kontrolü, tutyalar ve SUS sensör kalibrasyonu.",
    "desc_en": "Scheduled maintenance for Volvo Penta IPS 500-1200 pod drives: synthetic gear oil change, prop shaft dual seals, sacrificial anodes, and steering unit sensor calibration.",
    "keywords_tr": "volvo penta ips bakımı, ips pod sürücü servisi, ips şanzıman yağı, ips keçe değişimi, volvo ips arıza, bodrum volvo ips",
    "keywords_en": "volvo penta ips maintenance, ips pod drive service turkey, ips gear oil change, volvo ips repair bodrum marmaris"
  },
  {
    "id": "yanmar-common-rail-diagnostics",
    "file_tr": "blog-yanmar-common-rail-ariza-teshis-ve-bakim.html",
    "file_en": "blog-yanmar-common-rail-diesel-diagnostics-service.html",
    "category_tr": "Arıza & Teşhis",
    "category_en": "Diagnostics & Repair",
    "image": "assets/yanmar-4jh-6ly-ozel-servis.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Yanmar Common Rail Dizel Motorlarda Arıza Teşhisi ve Bakım | DM MARİN",
    "title_en": "Yanmar Common Rail Diesel Diagnostics & Scheduled Care | DM MARIN",
    "h1_tr": "Yanmar 4JH-CR ve 6LY Common Rail Motor Bakım ve Teşhis Rehberi",
    "h1_en": "Yanmar Common Rail Engine Diagnostics & Maintenance Guide",
    "desc_tr": "Yanmar 4JH45, 4JH57, 4JH80, 4JH110 ve 6LY serisi elektronik marin dizellerde yakıt rayı basıncı, enjektör kodlama, Y-COP arıza okuma ve kışlık bakım.",
    "desc_en": "Comprehensive guide for Yanmar 4JH and 6LY Common Rail marine diesels: fuel rail pressure sensors, injector coding, Y-COP diagnostics, and winter lay-up.",
    "keywords_tr": "yanmar common rail servis, yanmar 4jh80 bakım, yanmar y-cop arıza, yanmar diagnostik cihazı, kalamış yanmar servisi",
    "keywords_en": "yanmar common rail service, yanmar 4jh diagnostic, yanmar yacht engine turkey, gocek yanmar marine service"
  },
  {
    "id": "yanmar-dizel-duman-renkleri",
    "file_tr": "blog-yanmar-dizel-motor-duman-renkleri-ve-teshis.html",
    "file_en": "blog-marine-diesel-exhaust-smoke-color-diagnostics.html",
    "category_tr": "Arıza & Teşhis",
    "category_en": "Diagnostics & Repair",
    "image": "assets/dm-marin-ariza-tespit.webp",
    "read_tr": "5 dk",
    "read_en": "5 min",
    "title_tr": "Marin Dizel Motorlarda Duman Renkleri: Siyah, Beyaz ve Mavi Duman Teşhisi | DM MARİN",
    "title_en": "Marine Diesel Smoke Diagnostics: Black, White & Blue Smoke Analysis | DM MARIN",
    "h1_tr": "Marin Dizel Motorlarda Duman Renkleri: Siyah, Beyaz ve Mavi Duman Teşhisi",
    "h1_en": "Marine Diesel Smoke Diagnostics: Black, White & Blue Smoke Analysis",
    "desc_tr": "Tekne egzozundan çıkan siyah, beyaz ve mavi dumanın mühendislik nedenleri: Enjektör damlatması, turbo basınç kaybı, supap lastiği aşınması ve silindir kapağı su sızıntısı.",
    "desc_en": "Engineering causes of black, white, and blue yacht exhaust smoke: dripping injectors, turbo boost pressure drops, worn valve seals, and cylinder head gasket leaks.",
    "keywords_tr": "tekne motoru siyah duman, marin dizel beyaz duman, tekne egzoz dumanı arıza, enjektör arızası marin",
    "keywords_en": "marine diesel black smoke, yacht engine white smoke, blue diesel exhaust diagnostics, faulty marine injectors"
  },
  {
    "id": "man-mtu-marine-yuksek-devirli",
    "file_tr": "blog-man-mtu-marine-yuksek-devirli-dizel-bakimi.html",
    "file_en": "blog-man-mtu-marine-high-speed-diesel-service.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/man-marine-v8-v12-ozel-servis.webp",
    "read_tr": "8 dk",
    "read_en": "8 min",
    "title_tr": "MAN & MTU Marine V8/V12 Yüksek Güçlü Dizel Motor Bakımı | DM MARİN",
    "title_en": "MAN & MTU Marine V8/V12 High Performance Diesel Service | DM MARIN",
    "h1_tr": "MAN & MTU Marine V8/V12 Yüksek Güçlü Dizel Motor Bakımı",
    "h1_en": "MAN & MTU Marine V8/V12 High Performance Diesel Service",
    "desc_tr": "MAN i6, V8, V12 ve MTU Series 2000 Common Rail motorlarda W1/W2/W3/W4 bakım paketleri, intercooler ve turboşarj denetimleri, supap boşluk ayarları.",
    "desc_en": "Scheduled W1-W4 maintenance standards for MAN V8/V12 and MTU Series 2000 high-speed marine diesels: intercooler ultrasonic wash, turbo boost, and valve clearances.",
    "keywords_tr": "man marine v12 servis, mtu series 2000 bakım, man tekne motoru tamiri, mtu yetkili özel servis",
    "keywords_en": "man marine v12 service turkey, mtu series 2000 yacht engine overhaul, man yacht diesel bodrum istanbul"
  },
  {
    "id": "marin-jenerator-ariza-ve-deniz-suyu",
    "file_tr": "blog-marin-jenerator-ariza-ve-deniz-suyu-sogutma.html",
    "file_en": "blog-marine-generator-faults-sea-water-cooling.html",
    "category_tr": "Jeneratör & Enerji",
    "category_en": "Generator & Power",
    "image": "assets/marin-jenerator-servisi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Marin Jeneratör Arızaları ve Deniz Suyu Soğutma Sorunları | DM MARİN",
    "title_en": "Marine Generator Faults & Raw Water Cooling Solutions | DM MARIN",
    "h1_tr": "Marin Jeneratörlerde Deniz Suyu Soğutma ve Aşırı Hararet Arızaları",
    "h1_en": "Marine Generator Sea Water Cooling & Overheating Troubleshooting",
    "desc_tr": "Kohler, Onan ve Fischer Panda jeneratörlerde impeller parçalanması, deniz suyu emiş vanası tıkanıklığı, ısı eşanjörü kireçlenmesi ve LOC/Overheat hata kodları.",
    "desc_en": "Troubleshooting Kohler, Onan and Fischer Panda generators: impeller failure, sea strainer blockage, heat exchanger scale, and LOC/Overheat fault shutdown codes.",
    "keywords_tr": "tekne jeneratör hararet, kohler jeneratör su atmıyor, onan jeneratör duruyor, jeneratör impeller değişimi",
    "keywords_en": "marine generator overheating, kohler genset no water output, onan generator raw water impeller failure"
  },
  {
    "id": "fischer-panda-inverter-arizalari",
    "file_tr": "blog-fischer-panda-jenerator-bakimi-ve-inverter-arizalari.html",
    "file_en": "blog-fischer-panda-marine-generator-service-inverter.html",
    "category_tr": "Jeneratör & Enerji",
    "category_en": "Generator & Power",
    "image": "assets/marin-jenerator-servisi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Fischer Panda Kapsüllü Jeneratör ve iSeries Inverter Bakımı | DM MARİN",
    "title_en": "Fischer Panda Encapsulated Genset & iSeries Inverter Service | DM MARIN",
    "h1_tr": "Fischer Panda Jeneratör Bakımı ve iSeries Inverter Arızaları",
    "h1_en": "Fischer Panda Marine Generator Care & Inverter Diagnostics",
    "desc_tr": "Fischer Panda 4000s, 5000i, 8000i, 10000i ve 15000i modellerinde su soğutmalı alternatör, inverter güç kartı arızaları, yağ basınç müşürü ve kapsül havalandırması.",
    "desc_en": "Technical guide for Fischer Panda iSeries generators: water-cooled alternators, PMGI inverter failures, winding temperature sensors, and capsule ventilation.",
    "keywords_tr": "fischer panda servis, fischer panda inverter arıza, panda 5000i tamir, fischer panda jeneratör istanbul",
    "keywords_en": "fischer panda service turkey, fischer panda inverter fault, panda 8000i yacht genset maintenance"
  },
  {
    "id": "marin-klima-chiller-bakim",
    "file_tr": "blog-marin-klima-chiller-ariza-ve-bakim.html",
    "file_en": "blog-marine-air-conditioning-chiller-repair-maintenance.html",
    "category_tr": "Tesisat & Donanım",
    "category_en": "Propulsion & Deck",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Marin Klima ve Chiller Sistemlerinde Arıza Tespiti ve Bakım | DM MARİN",
    "title_en": "Yacht Air Conditioning & Chiller System Repair & Maintenance | DM MARIN",
    "h1_tr": "Marin Klima ve Chiller Soğutma Sistemleri Bakım Kılavuzu",
    "h1_en": "Yacht Marine Air Conditioning & Chiller Maintenance Guide",
    "desc_tr": "Dometic, Webasto, Marvair ve Condaria marin klimalarda HP/LP gaz basınç arızaları, deniz suyu sirkülasyon pompası kavitasyonu ve fancoil koku giderme bakımı.",
    "desc_en": "Marine HVAC troubleshooting for Dometic, Webasto and Condaria chillers: HP/LP pressure faults, sea water cooling pump cavitation, and fancoil disinfection.",
    "keywords_tr": "marin klima gaz dolumu, tekne kliması soğutmuyor, dometic chiller arıza, webasto marin klima servis",
    "keywords_en": "marine air conditioning gas charge, yacht chiller repair turkey, dometic marine hvac maintenance"
  },
  {
    "id": "saft-hizalama-pss-kece",
    "file_tr": "blog-saft-hizalama-ve-pss-saf-kece-bakimi.html",
    "file_en": "blog-shaft-alignment-pss-dripless-seal-maintenance.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Şaft Hizalama (Alignment) ve PSS Damlatmaz Şaft Keçesi Bakımı | DM MARİN",
    "title_en": "Propeller Shaft Alignment & PSS Dripless Seal Service | DM MARIN",
    "h1_tr": "Şaft Hizalama ve PSS Şaft Keçesi Bakım ve Ayar Kılavuzu",
    "h1_en": "Propeller Shaft Alignment & PSS Dripless Shaft Seal Maintenance",
    "desc_tr": "Lazerli şaft hizalama toleransları, motor takozu çökmesi, PSS mekanik salmastra körük gerginliği, karbon-rotor temas yüzeyi ve su enjeksiyon hattı güvenliği.",
    "desc_en": "Laser shaft alignment tolerances, engine mount sagging, PSS mechanical seal bellows tension, carbon-rotor mating surface, and raw water cooling injection.",
    "keywords_tr": "şaft hizalama tekne, pss şaft keçesi su akıtıyor, motor takozu ayarı, damlatmaz şaft kovanı",
    "keywords_en": "marine shaft alignment laser turkey, pss shaft seal leaking, yacht dripless shaft seal replacement"
  },
  {
    "id": "seakeeper-gyro-stabilizer-bakimi",
    "file_tr": "blog-seakeeper-gyro-stabilizer-bakimi.html",
    "file_en": "blog-seakeeper-gyro-stabilizer-maintenance-cooling.html",
    "category_tr": "Tesisat & Donanım",
    "category_en": "Propulsion & Deck",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Seakeeper Jiroskopik Stabilizatör Periyodik Bakımı ve Glikol Devresi | DM MARİN",
    "title_en": "Seakeeper Gyro Stabilizer Scheduled Service & Glycol Circuit | DM MARIN",
    "h1_tr": "Seakeeper Gyro Stabilizatör Yıllık Bakımı ve Soğutma Devresi",
    "h1_en": "Seakeeper Gyroscopic Stabilizer Annual Care & Cooling Circuit",
    "desc_tr": "Seakeeper 2, 3, 6, 9, 16, 18, 26 ve 35 modellerinde kapalı devre glikol değişimi, deniz suyu eşanjörü çinko anotları, hidrolik fren basıncı ve vakum küre kontrolleri.",
    "desc_en": "Scheduled service for Seakeeper 2 through 35 gyros: closed-loop glycol replacement, sea water zinc anodes, brake hydraulic pressure, and vacuum sphere diagnostics.",
    "keywords_tr": "seakeeper bakım, gyro stabilizatör arıza, seakeeper glikol değişimi, seakeeper servis bodrum istanbul",
    "keywords_en": "seakeeper service turkey, gyro stabilizer maintenance bodrum, seakeeper glycol cooling flush"
  },
  {
    "id": "tekne-aku-ve-lityum-donusumu",
    "file_tr": "blog-tekne-aku-secimi-ve-lityum-donusumu.html",
    "file_en": "blog-marine-battery-selection-lifepo4-lithium-conversion.html",
    "category_tr": "Elektrik & Akü",
    "category_en": "Electrical & Battery",
    "image": "assets/marin-elektrik-elektronik.webp",
    "read_tr": "8 dk",
    "read_en": "8 min",
    "title_tr": "Teknelerde AGM, Jel ve LiFePO4 Lityum Akü Dönüşüm Rehberi | DM MARİN",
    "title_en": "Yacht AGM, Gel & LiFePO4 Lithium Battery Upgrade Guide | DM MARIN",
    "h1_tr": "Teknelerde Akü Seçimi ve LiFePO4 Lityum Dönüşüm Kılavuzu",
    "h1_en": "Marine Battery Selection & LiFePO4 Lithium Conversion Guide",
    "desc_tr": "AGM ve Jel akülerden LiFePO4 lityum demir fosfat sistemlere geçişte BMS entegrasyonu, DC-DC alternatör şarj regülatörü ve yangın güvenliği standartları.",
    "desc_en": "Upgrading from AGM/Gel to LiFePO4 marine lithium: BMS integration, DC-DC alternator charging relays, Class-approved fuse protection, and safety protocols.",
    "keywords_tr": "tekne lityum akü dönüşümü, lifepo4 marin akü, tekne servis aküsü seçimi, victron bms ayarı",
    "keywords_en": "marine lithium battery conversion turkey, lifepo4 yacht energy setup, victron bms installation"
  },
  {
    "id": "kislik-tekne-motoru-antifriz",
    "file_tr": "blog-kislik-tekne-motoru-ve-antifriz-kislama.html",
    "file_en": "blog-yacht-winterizing-antifreeze-engine-protection.html",
    "category_tr": "Kışlama & Koruma",
    "category_en": "Winterizing & Corrosion",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Kışlık Tekne Motoru Kışlama ve Antifriz Koruma Kılavuzu | DM MARİN",
    "title_en": "Yacht Engine Winterizing & Antifreeze Protection Protocol | DM MARIN",
    "h1_tr": "Kışlık Tekne Motoru Kışlama ve Donmaya Karşı Koruma Protokolü",
    "h1_en": "Yacht Engine Winterization & Frost Protection Protocol",
    "desc_tr": "Ham su devresi donma çatlaklarını önlemek için toksik olmayan marin antifriz basılması, yakıt stabilizatörü ilavesi, korozyon önleyici sisleme yağı ve nem tahliyesi.",
    "desc_en": "Winterizing marine diesels and generators: non-toxic propylene glycol raw water flushing, fuel biocides, fogging internal cylinders, and humidity control.",
    "keywords_tr": "tekne motoru kışlama, kışlık marin antifriz, tekne motor kışlık bakım, tekne donma önleme",
    "keywords_en": "yacht engine winterization turkey, marine diesel antifreeze flush, winter lay-up yacht service"
  },
  {
    "id": "tutya-anot-galvanik-korozyon",
    "file_tr": "blog-tutya-anot-ve-galvanik-korozyon-korunma.html",
    "file_en": "blog-sacrificial-anodes-galvanic-corrosion-guide.html",
    "category_tr": "Kışlama & Koruma",
    "category_en": "Winterizing & Corrosion",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Teknelerde Tutya (Anot) Seçimi ve Galvanik Korozyon Önleme | DM MARİN",
    "title_en": "Sacrificial Anode Selection & Marine Galvanic Corrosion Protection | DM MARIN",
    "h1_tr": "Teknelerde Tutya (Anot) Seçimi ve Galvanik Korozyondan Korunma",
    "h1_en": "Sacrificial Anode Selection & Galvanic Corrosion Protection",
    "desc_tr": "Tuzlu su, acı su ve tatlı suda Çinko, Alüminyum ve Magnezyum anot seçimi. Şaft tutyaları, baş pervane anotları, motor blok çinkoları ve kaçak akım testleri.",
    "desc_en": "Selecting Zinc, Aluminum, and Magnesium sacrificial anodes for salt, brackish, and fresh water. Shaft anodes, bow thruster zincs, heat exchanger pencils, and stray current testing.",
    "keywords_tr": "tekne tutya değişimi, galvanik korozyon tekne, şaft tutyası çinko, motor blok tutyası",
    "keywords_en": "sacrificial zinc anodes yacht, marine galvanic corrosion prevention, bow thruster anode change"
  },
  {
    "id": "bow-thruster-bas-pervane-bakimi",
    "file_tr": "blog-bow-thruster-bas-pervane-bakimi.html",
    "file_en": "blog-bow-stern-thruster-maintenance-yacht.html",
    "category_tr": "Tesisat & Donanım",
    "category_en": "Propulsion & Deck",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "5 dk",
    "read_en": "5 min",
    "title_tr": "Baş & Kıç Pervane (Bow & Stern Thruster) Bakımı ve Arızaları | DM MARİN",
    "title_en": "Bow & Stern Thruster Maintenance, Oil & Solenoid Care | DM MARIN",
    "h1_tr": "Baş ve Kıç Pervane (Bow Thruster) Bakım ve Onarım Rehberi",
    "h1_en": "Bow and Stern Thruster Maintenance & Troubleshooting Guide",
    "desc_tr": "Side-Power (Sleipner), Quick, Max Power ve Vetus baş pervanelerde kuyruk yağı keçesi, röle kontak aşınması, karbon kömür değişimi ve tutya montajı.",
    "desc_en": "Scheduled service for Sleipner Side-Power, Quick, and Vetus thrusters: tailpiece gear oil seals, solenoid contact wear, carbon brush replacement, and anode renewal.",
    "keywords_tr": "bow thruster bakım, baş pervane su kaçırıyor, side-power servis, baş pervane kömür değişimi",
    "keywords_en": "bow thruster service turkey, side-power sleipner maintenance, yacht thruster solenoid repair"
  },
  {
    "id": "turbosarj-egzoz-manifoldu-bakimi",
    "file_tr": "blog-marin-turbosarj-ve-egzoz-manifoldu-bakimi.html",
    "file_en": "blog-marine-turbocharger-exhaust-elbow-inspection.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Marin Turboşarj ve Egzoz Dirseği (Mixing Elbow) Kontrolü | DM MARİN",
    "title_en": "Marine Turbocharger & Exhaust Mixing Elbow Inspection | DM MARIN",
    "h1_tr": "Marin Turboşarj ve Egzoz Dirseği (Mixing Elbow) Bakım Kılavuzu",
    "h1_en": "Marine Turbocharger & Exhaust Mixing Elbow Inspection Guide",
    "desc_tr": "Deniz suyu korozyonunun egzoz dirseğinde oluşturduğu delikler, turbo türbin pallerine geri su basması, wastegate sıkışması ve kompresör salyangoz temizliği.",
    "desc_en": "Diagnosing exhaust mixing elbow corrosion, sea water back-siphoning into turbochargers, seized wastegate actuators, and compressor ultrasonic cleaning.",
    "keywords_tr": "marin turbo tamiri, egzoz dirseği delinmesi tekne, mixing elbow su kaçağı, turbo wastegate sıkışması",
    "keywords_en": "marine turbocharger overhaul turkey, exhaust mixing elbow corrosion, yacht turbo boost pressure"
  },
  {
    "id": "su-yapici-watermaker-bakimi",
    "file_tr": "blog-tekne-su-yapici-watermaker-bakimi.html",
    "file_en": "blog-marine-watermaker-maintenance-winterizing.html",
    "category_tr": "Tesisat & Donanım",
    "category_en": "Propulsion & Deck",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Tekne Su Yapıcı (Watermaker) Membran Temizliği ve Kışlama | DM MARİN",
    "title_en": "Marine Watermaker Membrane Pickling & Scheduled Service | DM MARIN",
    "h1_tr": "Tekne Su Yapıcı (Watermaker) Membran Koruma ve Bakım Rehberi",
    "h1_en": "Marine Watermaker Reverse Osmosis Care & Pickling Guide",
    "desc_tr": "Idromar, Schenker, Sea Recovery ve Selmar su yapıcı sistemlerinde yüksek basınç pompası yağ değişimi, RO membran alkalik/asidik yıkama ve kışlık pickling koruması.",
    "desc_en": "Service standards for Idromar, Schenker, and Sea Recovery RO watermakers: HP pump oil change, chemical membrane descaling, and winter pickling biocides.",
    "keywords_tr": "su yapıcı kışlama, watermaker membran temizliği, tekne su yapıcı tamir, idromar servis bodrum",
    "keywords_en": "yacht watermaker membrane pickling, reverse osmosis marine service, idromar descaler turkey"
  },
  {
    "id": "yakit-deposu-ve-diesel-bug",
    "file_tr": "blog-tekne-yakit-deposu-temizligi-ve-diesel-bug.html",
    "file_en": "blog-yacht-fuel-tank-cleaning-diesel-bug-solution.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Tekne Yakıt Deposu Temizliği, Dizel Bakterisi (Diesel Bug) Çözümü | DM MARİN",
    "title_en": "Yacht Fuel Tank Cleaning & Diesel Bug Sludge Eradication | DM MARIN",
    "h1_tr": "Teknelerde Yakıt Tankı Temizliği ve Dizel Bakterisi Çözümü",
    "h1_en": "Yacht Fuel Tank Cleaning & Diesel Bug Microbial Remediation",
    "desc_tr": "Mazot tankının dibinde biriken su ve biyofilm çamurunun enjektörleri tıkamasını önleme, mekanik tank yıkama ve biyosit kimyasal dozlama yöntemleri.",
    "desc_en": "Preventing diesel bug microbial slime and water condensation from clogging Common Rail injectors: mechanical suction flushing and biocide fuel treatment.",
    "keywords_tr": "tekne mazot deposu temizliği, dizel bakterisi temizleme, tekne yakıt tankı yıkama, racor filtre dolması",
    "keywords_en": "yacht diesel bug treatment turkey, marine fuel tank cleaning, diesel fuel polishing bodrum"
  },
  {
    "id": "mobil-yakit-parlatma-tank-temizligi",
    "file_tr": "blog-mobil-yakit-parlatma-ve-tank-temizligi.html",
    "file_en": "blog-mobile-marine-fuel-polishing-tank-cleaning.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/dm-marin-ariza-tespit.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Mobil Yakıt Parlatma (Fuel Polishing) ve Tank Temizleme | DM MARİN",
    "title_en": "Mobile Marine Fuel Polishing & Filtration Service | DM MARIN",
    "h1_tr": "Mobil Yakıt Parlatma (Fuel Polishing) ve Filtrasyon Hizmeti",
    "h1_en": "Mobile Marine Fuel Polishing & Multi-Stage Filtration",
    "desc_tr": "Marinada tekneden yakıtı tahliye etmeden kapalı devre yüksek debili mikro-filtrasyon ve santrifüj su ayrıştırma ile yakıtın sıfır mikron saflığa getirilmesi.",
    "desc_en": "Closed-loop high flow fuel polishing on marina pontoons: centrifugal water separation, 2-micron filtration, and restoring degraded yacht diesel.",
    "keywords_tr": "mobil yakıt parlatma, fuel polishing tekne, mazot filtrasyonu marina, kalamış yakıt temizleme",
    "keywords_en": "mobile fuel polishing turkey, marine diesel centrifugal filtration, yacht fuel cleaning marmaris"
  },
  {
    "id": "cat-c18-c32-motor-bakimi",
    "file_tr": "blog-cat-c18-c32-marin-motor-bakimi.html",
    "file_en": "blog-cat-c18-c32-marine-diesel-service.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Caterpillar C12, C18 ve C32 ACERT Marin Motor Bakımı | DM MARİN",
    "title_en": "Caterpillar C12, C18 & C32 ACERT Marine Diesel Service | DM MARIN",
    "h1_tr": "Caterpillar C18 ve C32 ACERT Marin Dizel Motor Bakımı",
    "h1_en": "Caterpillar C18 & C32 ACERT Marine Engine Scheduled Care",
    "desc_tr": "Caterpillar ACERT yüksek güçlü megayat ana makinelerinde S•O•S yağ analizi, MEUI enjektör kalibrasyonu, şarj havası soğutucu testi ve 250/1000 saatlik revizyon.",
    "desc_en": "Scheduled service for Cat C12, C18, and C32 ACERT marine diesels: S•O•S fluid analysis, MEUI injector timing, aftercooler hydrostatic testing, and overhaul protocols.",
    "keywords_tr": "caterpillar c18 servis, cat c32 marin motor bakım, cat tekne motoru tamiri, cat enjektör kalibrasyonu",
    "keywords_en": "cat c18 marine diesel service turkey, caterpillar c32 yacht engine repair, cat marine injector timing"
  },
  {
    "id": "kohler-jenerator-ariza-kodlari",
    "file_tr": "blog-kohler-marin-jenerator-ariza-kodlari-ve-cozumleri.html",
    "file_en": "blog-kohler-marine-generator-fault-codes-troubleshooting.html",
    "category_tr": "Jeneratör & Enerji",
    "category_en": "Generator & Power",
    "image": "assets/marin-jenerator-servisi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Kohler Marin Jeneratör Arıza Kodları ve Çözüm Yolları | DM MARİN",
    "title_en": "Kohler Marine Generator Fault Codes & Troubleshooting Guide | DM MARIN",
    "h1_tr": "Kohler Marin Jeneratör Arıza Kodları ve Teşhis Rehberi",
    "h1_en": "Kohler Marine Generator Fault Codes & Troubleshooting",
    "desc_tr": "Kohler ADC 2100 ve Decision-Maker 3500 kontrol panellerinde LOC (Loss of Coolant), OP (Oil Pressure), OS (Over Speed), UF (Under Frequency) arızalarının giderilmesi.",
    "desc_en": "Decoding Kohler ADC 2100 & Decision-Maker controllers: LOC coolant loss, OP low oil pressure, OS overspeed, and UF under frequency troubleshooting.",
    "keywords_tr": "kohler jeneratör loc hatası, kohler arıza kodları, kohler marin jeneratör duruyor, kohler op hatası",
    "keywords_en": "kohler generator loc fault code, kohler marine genset error codes, kohler under frequency repair"
  },
  {
    "id": "zf-twin-disc-sanziman-bakimi",
    "file_tr": "blog-zf-twin-disc-marin-sanziman-bakimi.html",
    "file_en": "blog-zf-twin-disc-marine-transmission-service.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "ZF & Twin Disc Marin Şanzıman Bakımı ve Yağ Basıncı Ayarı | DM MARİN",
    "title_en": "ZF & Twin Disc Marine Transmission Service & Pressure Care | DM MARIN",
    "h1_tr": "ZF ve Twin Disc Marin Şanzıman Bakım ve Teşhis Rehberi",
    "h1_en": "ZF & Twin Disc Marine Transmission Maintenance Guide",
    "desc_tr": "ZF 25A, 45A, 63A, 85A ve Twin Disc şanzımanlarda hidrolik kavrama balata aşınması, ATF yağ soğutucu korozyonu, kontrol valfi selenoidi ve yağ basınç testi.",
    "desc_en": "Maintenance standards for ZF and Twin Disc marine gearboxes: hydraulic clutch disc wear, oil cooler zincs, solenoid valves, and shifting pressure adjustments.",
    "keywords_tr": "zf marin şanzıman servisi, twin disc tekne şanzıman tamiri, marin şanzıman kaydırıyor, şanzıman yağı basıncı tekne",
    "keywords_en": "zf marine transmission repair turkey, twin disc yacht gearbox overhaul, marine gearbox hydraulic pressure test"
  },
  {
    "id": "tekne-isi-esanjoru-aftercooler",
    "file_tr": "blog-tekne-isi-esanjoru-aftercooler-ultrasonik-temizleme.html",
    "file_en": "blog-marine-heat-exchanger-aftercooler-ultrasonic-cleaning.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Isı Eşanjörü ve Aftercooler Ultrasonik Temizleme ve Kireç Sökme | DM MARİN",
    "title_en": "Marine Heat Exchanger & Aftercooler Ultrasonic Descaling | DM MARIN",
    "h1_tr": "Isı Eşanjörü ve Aftercooler Ultrasonik Temizleme ve Kireç Sökme",
    "h1_en": "Marine Heat Exchanger & Aftercooler Ultrasonic Descaling Guide",
    "desc_tr": "Tuzlu su kireci, midye ve çamurla tıkanan bakır-nikel boru demetlerinin (bundle) kimyasal ve ultrasonik banyolarla sıfır dirence kavuşturulması ve motor hararetinin önlenmesi.",
    "desc_en": "Ultrasonic bath and eco-chemical descaling for marine heat exchanger tube bundles, aftercoolers, and intercoolers to restore thermal efficiency and prevent engine overheating.",
    "keywords_tr": "tekne eşanjör temizliği, aftercooler kireç sökme, marin ısı eşanjörü ultrasonik, tekne motor hararet önleme",
    "keywords_en": "marine heat exchanger cleaning turkey, aftercooler ultrasonic wash, yacht diesel cooling bundle descaling"
  },
  {
    "id": "victron-energy-lifepo4-bms",
    "file_tr": "blog-victron-energy-lifepo4-lityum-aku-bms-ayarlari.html",
    "file_en": "blog-victron-energy-lifepo4-lithium-bms-integration.html",
    "category_tr": "Elektrik & Akü",
    "category_en": "Electrical & Battery",
    "image": "assets/marin-elektrik-elektronik.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Victron Energy & LiFePO4 Marin Akü BMS Entegrasyon ve Şarj Ayarları | DM MARİN",
    "title_en": "Victron Energy & LiFePO4 Marine Lithium BMS Integration | DM MARIN",
    "h1_tr": "Victron Energy & LiFePO4 Marin Akü BMS Entegrasyon ve Şarj Ayarları",
    "h1_en": "Victron Energy & LiFePO4 Marine Lithium BMS Integration Guide",
    "desc_tr": "Victron MultiPlus inverter/charger, Cerbo GX ve SmartSolar MPPT cihazlarında LiFePO4 şarj voltajları, DVCC yönetimi ve alternatör koruma rölesi konfigürasyonu.",
    "desc_en": "Configuring Victron MultiPlus, Cerbo GX and SmartSolar MPPT for LiFePO4 marine batteries: charge profiles, DVCC closed-loop communication, and alternator protection relays.",
    "keywords_tr": "victron lityum akü ayarları, cerbo gx marin bms, victron multiplus tekne şarj, lifepo4 marin kurulum",
    "keywords_en": "victron energy marine lithium setup, cerbo gx bms integration, victron multiplus yacht charger configuration"
  },
  {
    "id": "marin-hidrolik-dumen-pasarella",
    "file_tr": "blog-marin-hidrolik-dumen-ve-pasarella-bakimi.html",
    "file_en": "blog-marine-hydraulic-steering-passerelle-maintenance.html",
    "category_tr": "Tesisat & Donanım",
    "category_en": "Propulsion & Deck",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Marin Hidrolik Dümen, Pasarella ve Yüzme Platformu Bakımı | DM MARİN",
    "title_en": "Yacht Hydraulic Steering, Passerelle & Swim Platform Service | DM MARIN",
    "h1_tr": "Marin Hidrolik Dümen, Pasarella ve Yüzme Platformu Bakımı",
    "h1_en": "Yacht Hydraulic Steering, Passerelle & Platform Maintenance",
    "desc_tr": "Besenzoni, Opacmare ve Opac hidrolik pasarellalarda yağ kaçağı tamiri, hidrolik ünite basınç testi, dümen pistonu keçeleri ve selenoid valf temizliği.",
    "desc_en": "Troubleshooting Besenzoni, Opacmare, and hydraulic steering systems: cylinder seal replacement, hydraulic power pack pressure calibration, and solenoid purging.",
    "keywords_tr": "besenzoni pasarella tamiri, tekne hidrolik dümen arıza, opacmare servis bodrum, hidrolik platform tamiri",
    "keywords_en": "besenzoni passerelle repair turkey, yacht hydraulic steering bleeding, opacmare gangway service marmaris"
  },
  {
    "id": "mobil-marin-servis-secimi",
    "file_tr": "blog-mobil-marin-servis-secimi-ve-marina-hizmetleri.html",
    "file_en": "blog-choosing-mobile-marine-engineering-service.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/acil-mobil-marin-servis.webp",
    "read_tr": "5 dk",
    "read_en": "5 min",
    "title_tr": "Mobil Marin Servis Seçerken Nelere Dikkat Edilmeli? | DM MARİN",
    "title_en": "How to Choose a Certified Mobile Marine Engineering Service | DM MARIN",
    "h1_tr": "Mobil Marin Servis Seçerken Dikkat Edilmesi Gereken 7 Kritik Kriter",
    "h1_en": "7 Critical Factors When Choosing a Mobile Marine Service",
    "desc_tr": "Marinada yerinde servis alırken yetki sertifikaları, OEM diagnostik cihaz donanımı, faturalı orijinal parça garantisi ve acil mobil intikal hızı rehberi.",
    "desc_en": "Essential checklist for hiring mobile marine engineers: OEM diagnostics tools, authorized insurance coverage, authentic spare parts warranties, and marina dispatch speed.",
    "keywords_tr": "mobil marin servis seçimi, yerinde tekne tamiri, tekne servisi istanbul, marina mobil servis kalamış",
    "keywords_en": "choosing mobile marine service, yacht engineer turkey, mobile boat repair istanbul bodrum"
  },
  {
    "id": "cummins-qsb-qsc-qsm-maintenance",
    "file_tr": "blog-cummins-qsb-qsc-qsm-marin-motor-bakimi.html",
    "file_en": "blog-cummins-qsb-qsc-qsm-marine-diesel-service.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Cummins QSB, QSC ve QSM Marin Dizel Motor Bakımı | DM MARİN",
    "title_en": "Cummins QSB, QSC & QSM Marine Diesel Scheduled Maintenance | DM MARIN",
    "h1_tr": "Cummins QSB 5.9/6.7, QSC 8.3 ve QSM 11 Marin Motor Bakım Rehberi",
    "h1_en": "Cummins QSB, QSC & QSM Marine Diesel Service & Diagnostics",
    "desc_tr": "Cummins Quantum serisi marin motorlarda SmartCraft diagnostik kodları, Walker AirSep hava filtresi bakımı, aftercooler basınç testi ve Venturi yağ filtreleme.",
    "desc_en": "Scheduled service for Cummins QSB 6.7, QSC 8.3, and QSM 11: SmartCraft diagnostics, Walker AirSep maintenance, aftercooler pressure testing, and Venturi filtration.",
    "keywords_tr": "cummins qsb servis, cummins qsc bakım, cummins tekne motoru tamiri, smartcraft arıza kodları",
    "keywords_en": "cummins qsb marine service turkey, cummins qsc 8.3 yacht repair, cummins qsm11 overhaul bodrum"
  },
  {
    "id": "northern-lights-generator-service",
    "file_tr": "blog-northern-lights-marin-jenerator-bakimi.html",
    "file_en": "blog-northern-lights-marine-generator-maintenance.html",
    "category_tr": "Jeneratör & Enerji",
    "category_en": "Generator & Power",
    "image": "assets/marin-jenerator-servisi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Northern Lights Marin Jeneratör Bakımı ve Lugger Blok Servisi | DM MARİN",
    "title_en": "Northern Lights Marine Generator & Lugger Engine Maintenance | DM MARIN",
    "h1_tr": "Northern Lights Ağır Hizmet Marin Jeneratör Bakım Kılavuzu",
    "h1_en": "Northern Lights Heavy Duty Marine Genset Service Protocol",
    "desc_tr": "Northern Lights 6kW - 40kW marin jeneratörlerde Lugger dizel blok bakımı, otomatik voltaj regülatörü (AVR), mekanik enjeksiyon pompası ve 500 saatlik revizyon.",
    "desc_en": "Scheduled care for Northern Lights 6-40kW gensets: Lugger diesel block maintenance, AVR voltage calibration, raw water pump rebuild, and 500-hour inspection.",
    "keywords_tr": "northern lights jeneratör servis, lugger motor bakım, northern lights tekne jeneratörü",
    "keywords_en": "northern lights generator service turkey, lugger marine diesel repair, yacht genset avr calibration"
  },
  {
    "id": "yamaha-suzuki-outboard-maintenance",
    "file_tr": "blog-yamaha-suzuki-distankma-motor-bakimi.html",
    "file_en": "blog-yamaha-suzuki-marine-outboard-maintenance-diagnostics.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Yamaha & Suzuki Dıştan Takma Marin Motor Periyodik Bakımı | DM MARİN",
    "title_en": "Yamaha & Suzuki Marine Outboard Maintenance & Diagnostics | DM MARIN",
    "h1_tr": "Yamaha V6/V8 ve Suzuki 4-Zamanlı Dıştan Takma Motor Bakımı",
    "h1_en": "Yamaha V6/V8 & Suzuki 4-Stroke Outboard Maintenance Guide",
    "desc_tr": "Yamaha F200-F425 ve Suzuki DF150-DF350 motorlarda alt kuyruk dişli yağı, su pompası impeller değişimi, VST buhar separatörü filtresi ve YDIS / SDS teşhisi.",
    "desc_en": "Scheduled service for Yamaha and Suzuki outboard engines: lower unit gear lube, water pump impeller renewal, VST fuel filter cleaning, and diagnostic software analysis.",
    "keywords_tr": "yamaha dıştan takma servis, suzuki df300 bakım, tekne dıştan takma motor tamiri, vst filtresi temizliği",
    "keywords_en": "yamaha outboard service turkey, suzuki marine diagnostics, outboard lower unit oil change istanbul"
  },
  {
    "id": "nmea-2000-marine-bus-integration",
    "file_tr": "blog-nmea-2000-ve-marin-canbus-ag-kurulumu.html",
    "file_en": "blog-nmea-2000-marine-canbus-network-troubleshooting.html",
    "category_tr": "Elektrik & Akü",
    "category_en": "Electrical & Battery",
    "image": "assets/marin-elektrik-elektronik.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "NMEA 2000 & Marin CAN-Bus Ağ Kurulumu ve Teşhis Rehberi | DM MARİN",
    "title_en": "NMEA 2000 & Marine CAN-Bus Network Setup & Troubleshooting | DM MARIN",
    "h1_tr": "NMEA 2000 ve Marin CAN-Bus Ağ Kurulumu ve Hata Giderme",
    "h1_en": "NMEA 2000 & Marine CAN-Bus Backbone Integration & Diagnostics",
    "desc_tr": "Raymarine SeaTalkNG, Garmin Marine Network ve Simrad SimNet omurga sonlandırma dirençleri, voltaj düşümü teşhisi ve motor verilerini chartplotter'a aktarma.",
    "desc_en": "Engineering guide for NMEA 2000 backbone networks: termination resistor testing, LEN load calculation, voltage drop analysis, and engine gauge gateway integration.",
    "keywords_tr": "nmea 2000 kurulum, seatalkng arıza, raymarine motor göstergesi, can bus tekne ağı",
    "keywords_en": "nmea 2000 marine network turkey, seatalkng backbone troubleshooting, engine data to chartplotter"
  },
  {
    "id": "marine-bilge-blackwater-pumps",
    "file_tr": "blog-sintine-ve-pis-su-hidrofor-pompa-arizalari.html",
    "file_en": "blog-marine-bilge-blackwater-macerator-pump-repair.html",
    "category_tr": "Tesisat & Donanım",
    "category_en": "Propulsion & Deck",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Sintine Pompaları, Pis Su Maceratör ve Hidrofor Arıza Tamiri | DM MARİN",
    "title_en": "Marine Bilge, Black Water Macerator & Fresh Water Pump Repair | DM MARIN",
    "h1_tr": "Sintine Pompaları, Pis Su Maceratör ve Hidrofor Arıza Tamiri",
    "h1_en": "Marine Bilge, Black Water Macerator & Fresh Water Pump Care",
    "desc_tr": "Rule, Jabsco ve Johnson otomatik sintine flatörleri, maceratör bıçak tıkanıklığı tamiri, hidrofor basınç şalteri ayarı ve çekvalf kaçak testleri.",
    "desc_en": "Troubleshooting yacht pumping systems: automatic float switch wiring, Jabsco macerator unjamming, fresh water pump pressure switch adjustment, and check valve sealing.",
    "keywords_tr": "sintine pompası çalışmıyor, maceratör tamiri tekne, tekne hidrofor arıza, jabsco pompa servis",
    "keywords_en": "marine bilge pump repair turkey, yacht macerator unjamming, fresh water pump pressure switch"
  },
  {
    "id": "mtu-series-4000-maintenance",
    "file_tr": "blog-mtu-series-4000-megayat-motor-bakimi.html",
    "file_en": "blog-mtu-series-4000-superyacht-diesel-maintenance.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/mtu-series-2000-ozel-servis.webp",
    "read_tr": "8 dk",
    "read_en": "8 min",
    "title_tr": "MTU Series 4000 Megayat Dizel Motor Bakım Standartları | DM MARİN",
    "title_en": "MTU Series 4000 Superyacht Diesel Service Standards | DM MARIN",
    "h1_tr": "MTU Series 4000 Megayat Motor Bakım ve Teşhis Kılavuzu",
    "h1_en": "MTU Series 4000 Superyacht Engine Scheduled Maintenance",
    "desc_tr": "MTU 12V4000 ve 16V4000 Common Rail megayat motorlarında ADEC elektronik yönetim sistemi, santrifüj yağ seperatörü, endoskopik silindir kontrolü ve QL2 revizyonu.",
    "desc_en": "Megayacht engineering protocols for MTU 12V/16V 4000 engines: ADEC engine management, centrifugal oil cleaner service, borescope cylinder inspection, and QL2 overhaul.",
    "keywords_tr": "mtu 4000 megayat servis, mtu adec arıza teşhis, mtu 16v4000 bakım bodrum, mtu süperyat servisi",
    "keywords_en": "mtu series 4000 service turkey, superyacht mtu engine overhaul, mtu adec diagnostics bodrum"
  },
  {
    "id": "coelmo-marine-generator-service",
    "file_tr": "blog-coelmo-marin-jenerator-servisi-ve-bakimi.html",
    "file_en": "blog-coelmo-marine-generator-service-troubleshooting.html",
    "category_tr": "Jeneratör & Enerji",
    "category_en": "Generator & Power",
    "image": "assets/marin-jenerator-servisi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Coelmo Marin Jeneratör Servisi, FDC Kontrol ve Bakım | DM MARİN",
    "title_en": "Coelmo Marine Generator Service & FDC Panel Troubleshooting | DM MARIN",
    "h1_tr": "Coelmo Marin Jeneratör Bakımı ve FDC Dijital Panel Arızaları",
    "h1_en": "Coelmo Marine Generator Care & FDC Digital Panel Diagnostics",
    "desc_tr": "Coelmo DM350, DM600, DM900 ve DMB serisi marin jeneratörlerde Kubota dizel blok bakımı, FDC kontrol paneli hata kodları, deniz suyu pompası keçeleri ve kışlama.",
    "desc_en": "Scheduled service for Coelmo DM and DMB series marine generators: Kubota block care, FDC digital panel alarms, sea water pump mechanical seals, and winter lay-up.",
    "keywords_tr": "coelmo jeneratör servis, coelmo fdc arıza, coelmo tekne jeneratörü bakım, coelmo istanbul",
    "keywords_en": "coelmo marine generator service turkey, coelmo fdc alarm reset, coelmo yacht genset repair"
  },
  {
    "id": "nanni-diesel-toyota-kubota",
    "file_tr": "blog-nanni-diesel-marin-motor-bakimi-ve-arizalar.html",
    "file_en": "blog-nanni-diesel-marine-engine-service-diagnostics.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Nanni Diesel Marin Motor Bakımı (Kubota & Toyota Bazlı) | DM MARİN",
    "title_en": "Nanni Diesel Marine Engine Service (Kubota & Toyota Blocks) | DM MARIN",
    "h1_tr": "Nanni Diesel Marin Motor Bakım ve Arıza Teşhis Rehberi",
    "h1_en": "Nanni Diesel Marine Engine Maintenance & Diagnostics",
    "desc_tr": "Nanni N2, N3, N4 (Kubota bazlı) ve T4, T6 (Toyota bazlı) marin dizellerde ısı eşanjörü temizliği, triger kayışı değişimi, enjektör ayarı ve deniz suyu pompası revizyonu.",
    "desc_en": "Technical guide for Nanni Diesel engines: Kubota and Toyota block marinization, heat exchanger ultrasonic flushing, timing belt replacement, and fuel injection timing.",
    "keywords_tr": "nanni diesel servis, nanni motor bakım, nanni kubota marin yedek parça, nanni toyota tekne motoru",
    "keywords_en": "nanni diesel service turkey, nanni marine engine repair, nanni kubota spare parts istanbul"
  },
  {
    "id": "westerbeke-generator-service",
    "file_tr": "blog-westerbeke-marin-jenerator-bakimi-ve-karburator.html",
    "file_en": "blog-westerbeke-marine-generator-service-carburetor.html",
    "category_tr": "Jeneratör & Enerji",
    "category_en": "Generator & Power",
    "image": "assets/marin-jenerator-servisi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Westerbeke Marin Jeneratör Bakımı, Karbüratör ve Enjeksiyon | DM MARİN",
    "title_en": "Westerbeke Marine Generator Care & Electronic Troubleshooting | DM MARIN",
    "h1_tr": "Westerbeke Marin Jeneratör Bakım ve Teşhis Kılavuzu",
    "h1_en": "Westerbeke Marine Generator Maintenance & Diagnostics",
    "desc_tr": "Westerbeke benzinli ve dizel kompakt marin jeneratörlerde governor hız regülatörü ayarı, karbüratör temizliği, egzoz sıcaklık sensörü ve kışlık koruma.",
    "desc_en": "Scheduled service for Westerbeke marine gensets: electronic governor adjustment, carburetor ultrasonic cleaning, exhaust high-temp switch testing, and winterization.",
    "keywords_tr": "westerbeke jeneratör servis, westerbeke karbüratör temizlik, westerbeke tekne jeneratörü",
    "keywords_en": "westerbeke generator service turkey, westerbeke marine repair, westerbeke yacht genset parts"
  },
  {
    "id": "baudouin-marine-propulsion",
    "file_tr": "blog-baudouin-marin-motor-servisi-ve-bakimi.html",
    "file_en": "blog-baudouin-marine-diesel-propulsion-service.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Baudouin Ağır Hizmet Ticari ve Yat Motoru Bakımı | DM MARİN",
    "title_en": "Baudouin Heavy Duty Commercial & Yacht Diesel Service | DM MARIN",
    "h1_tr": "Baudouin Marin Motor Bakım ve Ağır Hizmet Protokolü",
    "h1_en": "Baudouin Marine Diesel Heavy Duty Maintenance Protocol",
    "desc_tr": "Baudouin 6M26, 8M26 ve 12M26 serisi mekanik ve elektronik Common Rail marin motorlarda silindir kapağı torklama, turbo şarj basınç testi ve yağ analiz standartları.",
    "desc_en": "Engineering standards for Baudouin 6M, 8M and 12M commercial and superyacht diesels: cylinder head retorquing, turbo boost diagnostics, and heavy-duty filtration.",
    "keywords_tr": "baudouin motor servis, baudouin marin dizel bakım, baudouin tekne motoru tamiri",
    "keywords_en": "baudouin marine diesel service turkey, baudouin engine overhaul, commercial yacht propulsion"
  },
  {
    "id": "marine-fire-suppression-systems",
    "file_tr": "blog-makine-dairesi-otomatik-yangin-sondurme-fm200.html",
    "file_en": "blog-engine-room-fire-suppression-fm200-novec-1230.html",
    "category_tr": "Tesisat & Donanım",
    "category_en": "Propulsion & Deck",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Makine Dairesi Otomatik Yangın Söndürme (FM-200 & Novec 1230) | DM MARİN",
    "title_en": "Engine Room Automatic Fire Suppression (FM-200 & Novec 1230) | DM MARIN",
    "h1_tr": "Makine Dairesi Otomatik Yangın Söndürme Sistemleri Bakımı",
    "h1_en": "Engine Room Fire Suppression Systems (FM-200 & Novec) Care",
    "desc_tr": "Sea-Fire ve Fireboy otomatik makine dairesi gazlı yangın söndürme sistemlerinde basınç göstergesi kontrolü, otomatik motor stop rölesi testi ve hidrostatik tüp testleri.",
    "desc_en": "Maintenance protocol for Sea-Fire and Fireboy FM-200/Novec 1230 marine systems: pressure gauge inspection, engine shutdown interlock testing, and hydrostatic recertification.",
    "keywords_tr": "tekne yangın söndürme sistemi, fm200 makine dairesi yangın, sea-fire servis tekne, fireboy yangın tüpü",
    "keywords_en": "marine fire suppression service turkey, engine room fm200 test, sea-fire yacht inspection"
  },
  {
    "id": "pre-purchase-yacht-survey-engine",
    "file_tr": "blog-tekne-alim-oncesi-motor-ve-mekanik-ekspertiz.html",
    "file_en": "blog-pre-purchase-yacht-engine-mechanical-survey.html",
    "category_tr": "Arıza & Teşhis",
    "category_en": "Diagnostics & Repair",
    "image": "assets/dm-marin-ariza-tespit.webp",
    "read_tr": "8 dk",
    "read_en": "8 min",
    "title_tr": "Tekne Alım Öncesi Motor & Mekanik Ekspertiz Rehberi | DM MARİN",
    "title_en": "Pre-Purchase Marine Engine & Mechanical Survey Checklist | DM MARIN",
    "h1_tr": "İkinci El Tekne Alımında Motor ve Mekanik Ekspertiz Rehberi",
    "h1_en": "Pre-Purchase Yacht Engine & Mechanical Inspection Guide",
    "desc_tr": "Tekne satın alırken bilgisayarlı diagnostik motor saat analizi, karter kompresyon testi, şanzıman kaydırma kontrolü, eşanjör endoskopisi ve spektrografik yağ analizi.",
    "desc_en": "Critical pre-purchase marine survey checklist: OEM electronic engine hour verification, cylinder compression, gearbox slippage test, borescope cooling pass, and oil lab analysis.",
    "keywords_tr": "tekne motor ekspertiz, tekne alım öncesi kontrol, marin dizel kompresyon testi, tekne diagnostik rapor",
    "keywords_en": "pre-purchase yacht engine survey turkey, marine diesel inspection report, boat mechanical audit"
  },
  {
    "id": "deep-sea-electronics-genset-controllers",
    "file_tr": "blog-deep-sea-electronics-dse-jenerator-kontrol-paneli.html",
    "file_en": "blog-deep-sea-electronics-dse-generator-controller-setup.html",
    "category_tr": "Jeneratör & Enerji",
    "category_en": "Generator & Power",
    "image": "assets/marin-jenerator-servisi.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Deep Sea Electronics (DSE) Marin Jeneratör Kontrol Paneli Ayarları | DM MARİN",
    "title_en": "Deep Sea Electronics (DSE) Marine Genset Controller Configuration | DM MARIN",
    "h1_tr": "Deep Sea Electronics (DSE) Jeneratör Kontrol Paneli Ayar ve Arızaları",
    "h1_en": "Deep Sea Electronics (DSE) Marine Genset Controller Setup",
    "desc_tr": "DSE 6110, 7310 ve 8610 senkron kontrol panellerinde jeneratör paralel bağlama, yük paylaşımı, frekans/voltaj koruma alarmları ve otomatik jeneratör transfer (ATS) ayarları.",
    "desc_en": "Configuring DSE 6110, 7310, and 8610 controllers for marine generators: parallel synchronization, load sharing, frequency alarms, and automatic transfer switches.",
    "keywords_tr": "dse jeneratör paneli ayarı, deep sea electronics servis, jeneratör senkronizasyon tekne",
    "keywords_en": "deep sea electronics marine service turkey, dse generator controller setup, yacht genset load sharing"
  },
  {
    "id": "marine-alternator-external-regulator",
    "file_tr": "blog-marin-alternator-ve-harici-regulator-balmar.html",
    "file_en": "blog-high-output-marine-alternator-balmar-regulator-tuning.html",
    "category_tr": "Elektrik & Akü",
    "category_en": "Electrical & Battery",
    "image": "assets/marin-elektrik-elektronik.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Yüksek Akımlı Marin Alternatör ve Balmar Harici Regülatör | DM MARİN",
    "title_en": "High-Output Marine Alternator & Balmar External Regulator Tuning | DM MARIN",
    "h1_tr": "Yüksek Akımlı Marin Alternatör ve Balmar Regülatör Ayar Kılavuzu",
    "h1_en": "High-Output Marine Alternator & Balmar Regulator Setup Guide",
    "desc_tr": "Balmar, Mastervolt ve Prestolite yüksek akım alternatörlerde LiFePO4 şarjı için ısı sensörü entegrasyonu, kayış yükü ayarı ve alternatör aşırı ısınma koruması.",
    "desc_en": "Tuning high-output marine alternators with Balmar Max Charge regulators: alternator temperature sensors, Belt Load Manager, and LiFePO4 multi-stage charge profiles.",
    "keywords_tr": "balmar alternatör regülatörü, yüksek akım tekne alternatörü, tekne alternatör lityum şarj",
    "keywords_en": "balmar marine alternator setup turkey, high output yacht alternator, balmar max charge lithium"
  },
  {
    "id": "passerelle-teak-and-stainless-care",
    "file_tr": "blog-pasarella-ve-hidrolik-platform-mekanik-bakimi.html",
    "file_en": "blog-hydraulic-passerelle-swim-platform-mechanical-service.html",
    "category_tr": "Tesisat & Donanım",
    "category_en": "Propulsion & Deck",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Hidrolik Pasarella, Vinç ve Yüzme Platformu Mekanik Bakımı | DM MARİN",
    "title_en": "Hydraulic Passerelle, Crane & Swim Platform Mechanical Service | DM MARIN",
    "h1_tr": "Hidrolik Pasarella, Vinç ve Yüzme Platformu Mekanik Bakımı",
    "h1_en": "Hydraulic Passerelle, Crane & Swim Platform Mechanical Care",
    "desc_tr": "Besenzoni, Opacmare ve Pin-Craft hidrolik pasarellalarda paslanmaz çelik mafsal yağlaması, taşıyıcı kablo gergisi, mikroswitch limit sensörleri ve acil manuel indirme.",
    "desc_en": "Mechanical care for Besenzoni and Opacmare yacht gangways: 316L stainless joint lubrication, wire rope tensioning, limit microswitches, and emergency manual release bypass.",
    "keywords_tr": "pasarella mekanik bakım, besenzoni hidrolik tamir, tekne platform pistonu, pasarella selenoid arıza",
    "keywords_en": "hydraulic gangway repair turkey, besenzoni passerelle maintenance, yacht swim platform hydraulics"
  },
  {
    "id": "propeller-cavitation-and-pitch",
    "file_tr": "blog-pervane-kavitasyonu-hatve-pitch-ve-titresim-arizasi.html",
    "file_en": "blog-propeller-cavitation-pitch-vibration-diagnostics.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Pervane Kavitasyonu, Hatve (Pitch) ve Titreşim Arıza Teşhisi | DM MARİN",
    "title_en": "Marine Propeller Cavitation, Pitch & Vibration Diagnostics | DM MARIN",
    "h1_tr": "Pervane Kavitasyonu, Hatve (Pitch) Ayarı ve Titreşim Teşhisi",
    "h1_en": "Marine Propeller Cavitation, Pitch Adjustment & Vibration Analysis",
    "desc_tr": "Pervane pallerinde kavitasyon erozyonu, yanlış hatve (over-propped/under-propped) nedeniyle motorun devir alamaması, şaft salgısı ve dinamik balans alma.",
    "desc_en": "Diagnosing propeller cavitation pitting, over-propping engine RPM limitations, shaft runout optical measurements, and dynamic propeller balancing.",
    "keywords_tr": "tekne pervane kavitasyonu, pervane hatve ayarı, şaft titreşim yapıyor, tekne devir alamıyor pervane",
    "keywords_en": "marine propeller cavitation repair turkey, yacht propeller pitch optimization, shaft vibration test"
  },
  {
    "id": "marine-galvanic-isolator-transformer",
    "file_tr": "blog-galvanik-izolator-ve-izolasyon-transformatoru.html",
    "file_en": "blog-galvanic-isolator-vs-isolation-transformer-yacht.html",
    "category_tr": "Elektrik & Akü",
    "category_en": "Electrical & Battery",
    "image": "assets/marin-elektrik-elektronik.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Galvanik İzolatör vs İzolasyon Transformatörü Farkları | DM MARİN",
    "title_en": "Galvanic Isolator vs Isolation Transformer for Yacht Shore Power | DM MARIN",
    "h1_tr": "Galvanik İzolatör ve İzolasyon Transformatörü Kılavuzu",
    "h1_en": "Galvanic Isolator vs Isolation Transformer Yacht Shore Power Guide",
    "desc_tr": "Sahil besleme hattından gelen kaçak akımların tutyaları hızla eritmesini önleme, Victron izolasyon transformatörü montajı ve toprak hattı güvenlik standartları.",
    "desc_en": "Preventing rapid zinc anode depletion from marina shore power stray currents: galvanic isolator diodes vs toroidal isolation transformers and grounding standards.",
    "keywords_tr": "galvanik izolatör tekne, victron izolasyon trafosu, sahil besleme kaçak akım, tutya hızlı bitiyor",
    "keywords_en": "marine galvanic isolator turkey, yacht isolation transformer installation, shore power electrolysis"
  },
  {
    "id": "fuel-cooler-and-gear-cooler-descaling",
    "file_tr": "blog-yakit-ve-sanziman-yag-sogutucu-temizligi.html",
    "file_en": "blog-fuel-cooler-marine-gearbox-oil-cooler-descaling.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Yakıt Soğutucu ve Şanzıman Yağ Eşanjörü Temizliği | DM MARİN",
    "title_en": "Fuel Cooler & Marine Transmission Oil Cooler Ultrasonic Flushing | DM MARIN",
    "h1_tr": "Yakıt ve Şanzıman Yağ Soğutucu Eşanjör Temizlik Rehberi",
    "h1_en": "Fuel Cooler & Marine Gearbox Oil Cooler Maintenance Guide",
    "desc_tr": "Common Rail yüksek basınç dönüş yakıtının ve şanzıman hidrolik yağının aşırı ısınmasını önleyen marin eşanjörlerde çinko anot kontrolü ve kimyasal kireç giderme.",
    "desc_en": "Preventing Common Rail high fuel return temperatures and gearbox fluid overheating: ultrasonic descaling of marine tube coolers and sacrificial anode renewal.",
    "keywords_tr": "yakıt soğutucu kireç temizliği, şanzıman yağ eşanjörü delinmesi, marin yakıt harareti",
    "keywords_en": "marine fuel cooler cleaning turkey, transmission oil cooler flush, yacht gearbox overheat"
  },
  {
    "id": "raw-water-sea-strainer-maintenance",
    "file_tr": "blog-deniz-suyu-emiss-filtresi-ve-vana-guvenligi.html",
    "file_en": "blog-sea-strainer-thru-hull-seacock-safety-maintenance.html",
    "category_tr": "Tesisat & Donanım",
    "category_en": "Propulsion & Deck",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "5 dk",
    "read_en": "5 min",
    "title_tr": "Deniz Suyu Emiş Filtresi (Sea Strainer) ve Vana Güvenliği | DM MARİN",
    "title_en": "Sea Strainer & Thru-Hull Seacock Valve Safety & Care | DM MARIN",
    "h1_tr": "Deniz Suyu Emiş Filtresi ve Kinistin Vana Bakım Rehberi",
    "h1_en": "Sea Strainer & Thru-Hull Seacock Maintenance Protocol",
    "desc_tr": "Groco ve Vetus deniz suyu filtrelerinde sepet temizliği, akrilik kapak O-ring keçeleri, bronz kinistin vana tutukluk giderme ve korozyon testleri.",
    "desc_en": "Inspection protocols for Groco and Vetus raw water strainers: basket debris clearing, acrylic lid O-ring seals, DZR brass seacock lubrication, and bonding checks.",
    "keywords_tr": "deniz suyu filtresi temizliği tekne, kinistin vana sıkıştı, deniz suyu emiş vanası marin",
    "keywords_en": "marine sea strainer cleaning turkey, thru-hull seacock valve maintenance, yacht intake strainer"
  },
  {
    "id": "anchor-windlass-capstan-service",
    "file_tr": "blog-elektrikli-ve-hidrolik-irgat-bakimi.html",
    "file_en": "blog-electric-hydraulic-anchor-windlass-capstan-service.html",
    "category_tr": "Tesisat & Donanım",
    "category_en": "Propulsion & Deck",
    "image": "assets/dm-marin-tamir-atolyesi.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Elektrikli ve Hidrolik Irgat (Windlass) Periyodik Bakımı | DM MARİN",
    "title_en": "Electric & Hydraulic Anchor Windlass Scheduled Maintenance | DM MARIN",
    "h1_tr": "Tekne Irgatı (Windlass) Dişli Kutusu ve Motor Bakımı",
    "h1_en": "Yacht Anchor Windlass Gearbox & Electric Motor Service",
    "desc_tr": "Lofrans, Lewmar, Quick ve Maxwell ırgatlarda konik debriyaj (clutch) ayarı, sonsuz vida dişli yağı değişimi, ayak butonu rölesi ve motor kömürleri.",
    "desc_en": "Scheduled service for Lofrans, Lewmar, and Quick anchor windlasses: cone clutch adjustment, worm gearbox oil renewal, heavy-duty foot switch solenoids, and motor brushes.",
    "keywords_tr": "tekne ırgatı kaçırıyor, lewmar ırgat tamiri, lofrans ırgat kömür değişimi, ırgat dişli yağı",
    "keywords_en": "anchor windlass repair turkey, lewmar windlass service, lofrans yacht windlass gearbox oil"
  },
  {
    "id": "diesel-exhaust-riser-injection-elbow",
    "file_tr": "blog-egzoz-yukseltme-dirsegi-exhaust-riser-bakimi.html",
    "file_en": "blog-marine-exhaust-riser-waterlock-muffler-safety.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Egzoz Yükseltme Dirseği (Exhaust Riser) ve Waterlock Güvenliği | DM MARİN",
    "title_en": "Marine Exhaust Riser & Waterlock Muffler Safety Inspection | DM MARIN",
    "h1_tr": "Egzoz Yükseltme Dirseği (Riser) ve Waterlock Güvenlik Protokolü",
    "h1_en": "Marine Exhaust Riser & Waterlock Muffler Safety Protocol",
    "desc_tr": "Su hattının altında kalan motorlarda egzozdan motora geri su basmasını (siphoning) engelleyen antisifon valfi, paslanmaz riser kaynak korozyonu ve Vetus waterlock.",
    "desc_en": "Preventing catastrophic exhaust water back-siphoning into marine cylinders: anti-siphon loop vacuum valve testing, 316L riser weld inspection, and waterlock muffler drainage.",
    "keywords_tr": "exhaust riser tekne, egzozdan motora su kaçması, antisifon valfi marin, waterlock susturucu",
    "keywords_en": "marine exhaust riser inspection turkey, anti-siphon loop yacht valve, waterlock muffler leak"
  },
  {
    "id": "inverter-charger-battery-temperature-sensor",
    "file_tr": "blog-inverter-charger-ve-isi-sensoru-kalibrasyonu.html",
    "file_en": "blog-inverter-charger-temperature-sensor-voltage-drop.html",
    "category_tr": "Elektrik & Akü",
    "category_en": "Electrical & Battery",
    "image": "assets/marin-elektrik-elektronik.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Inverter/Charger Sıcaklık Sensörü ve Voltaj Düşümü Ayarları | DM MARİN",
    "title_en": "Inverter/Charger Temperature Compensation & Voltage Sense | DM MARIN",
    "h1_tr": "Inverter/Charger Sıcaklık Telafisi ve Voltaj Düşümü Ayarları",
    "h1_en": "Marine Inverter/Charger Temperature Sensing & Voltage Drop Care",
    "desc_tr": "Mastervolt Mass Combi ve Victron MultiPlus cihazlarında akü sıcaklık sensörü (BTS) ile termal kaçak (thermal runaway) önleme ve 4-kutuplu şarj profil ayarları.",
    "desc_en": "Calibrating temperature compensation sensors on Mastervolt and Victron inverter/chargers: preventing battery thermal runaway and configuring remote voltage sense wiring.",
    "keywords_tr": "inverter charger akü şarj ayarı, victron sıcaklık sensörü, akü aşırı ısınma koruması",
    "keywords_en": "marine inverter charger calibration turkey, victron battery temp sensor, yacht voltage drop compensation"
  },
  {
    "id": "marine-fuel-cooler-pressure-regulator",
    "file_tr": "blog-common-rail-yakit-rayi-ve-basinc-regulatoru.html",
    "file_en": "blog-common-rail-high-pressure-fuel-pump-rail-diagnostics.html",
    "category_tr": "Arıza & Teşhis",
    "category_en": "Diagnostics & Repair",
    "image": "assets/dm-marin-ariza-tespit.webp",
    "read_tr": "7 dk",
    "read_en": "7 min",
    "title_tr": "Common Rail Yüksek Basınç Pompası ve Yakıt Rayı Teşhisi | DM MARİN",
    "title_en": "Common Rail High Pressure Fuel Pump & Rail Sensor Diagnostics | DM MARIN",
    "h1_tr": "Common Rail Yüksek Basınç Pompası ve Yakıt Rayı Teşhis Kılavuzu",
    "h1_en": "Common Rail High-Pressure Fuel Pump & Fuel Rail Diagnostics",
    "desc_tr": "Bosch CP3/CP4 yüksek basınç pompalarında metal talaşı aşınması, yakıt rayı basınç regülatörü (SCV/FPROP) dalgalanması ve Common Rail basınç düşüm testleri.",
    "desc_en": "Diagnostics for Bosch CP3/CP4 marine high pressure fuel pumps: metal contamination inspection, fuel rail pressure regulator valve (SCV) calibration, and cranking pressure leak-off tests.",
    "keywords_tr": "common rail pompa arızası tekne, yakıt rayı basınç hatası, bosch cp4 marin mazot pompası",
    "keywords_en": "marine common rail pump diagnostics turkey, fuel rail pressure sensor yacht, bosch cp3 fuel pump repair"
  },
  {
    "id": "shaft-cutless-bearing-and-propeller-clearance",
    "file_tr": "blog-braket-ve-kovan-lastigi-cutless-bearing-degisimi.html",
    "file_en": "blog-cutless-bearing-shaft-bracket-wear-replacement.html",
    "category_tr": "Motor & Mekanik Bakım",
    "category_en": "Engine & Mechanical",
    "image": "assets/motor-mekanik-bakim.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Kovan Lastiği (Cutless Bearing) Değişimi ve Braket Boşluğu | DM MARİN",
    "title_en": "Cutless Bearing Replacement & Propeller Shaft Strut Clearance | DM MARIN",
    "h1_tr": "Kovan Lastiği (Cutless Bearing) Aşınma ve Değişim Rehberi",
    "h1_en": "Cutless Bearing Wear Inspection & Strut Replacement Guide",
    "desc_tr": "Şaft braketi ve kovan içi kauçuk yataklarda (cutless bearing) boşluk toleransı ölçümü, sentil çakısı ile aşınma tespiti, hidrolik çektirme ile kovan lastiği değişimi.",
    "desc_en": "Measuring cutless bearing radial play tolerances, feeler gauge strut clearance testing, hydraulic puller removal techniques, and water lubrication channel checks.",
    "keywords_tr": "kovan lastiği değişimi, cutless bearing boşluk tekne, şaft braket lastiği, pervane şaftı boşluk",
    "keywords_en": "cutless bearing replacement turkey, marine shaft strut bearing repair, yacht cutlass bearing clearance"
  },
  {
    "id": "winter-yacht-dehumidification-and-battery-float",
    "file_tr": "blog-kislik-tekne-nem-kontrolu-ve-aku-tampon-sarj.html",
    "file_en": "blog-winter-yacht-dehumidification-battery-float-maintenance.html",
    "category_tr": "Kışlama & Koruma",
    "category_en": "Winterizing & Corrosion",
    "image": "assets/marin-elektrik-elektronik.webp",
    "read_tr": "6 dk",
    "read_en": "6 min",
    "title_tr": "Kışlık Tekne Nem Alma ve Akü Tampon (Float) Şarj Yönetimi | DM MARİN",
    "title_en": "Winter Yacht Dehumidification & Smart Battery Float Maintenance | DM MARIN",
    "h1_tr": "Kış Dönemi Tekne Nem Kontrolü ve Akü Tampon Şarj Yönetimi",
    "h1_en": "Winter Yacht Humidity Management & Battery Float Charging",
    "desc_tr": "Kış aylarında sintine ve kabin küflenmesini önleyen kompresörlü nem alma cihazları, solar akü tampon şarj yönetimi ve kışlık periyodik marin nöbet kontrolleri.",
    "desc_en": "Managing winter yacht cabin humidity and mold prevention: compressor dehumidifiers, smart solar trickle chargers, and bi-weekly marina engineering checkups.",
    "keywords_tr": "tekne kışlık nem alma, tekne akü tampon şarj, kışlık tekne bakım kalamış, tekne küf önleme",
    "keywords_en": "winter yacht dehumidifier turkey, marine battery float charging, yacht winter guard service"
  }
];

console.log("======================================================================");
console.log("🤖 DM MARİN OTONOM SCRIBE-SEO BLOG VE REHBER ÜRETİM MOTORU");
console.log("📚 Maksimum Blog Tavanı: " + MAX_BLOG_LIMIT + " Makale (50 TR + 50 EN)");
console.log("======================================================================");

let activeCount = TOPIC_CATALOG.length * 2;
console.log(`✓ Mevcut Aktif Makale Sayısı: ${activeCount} / ${MAX_BLOG_LIMIT} (%100 Tam Kapasite)`);
console.log("✓ Tüm makaleler Schema.org JSON-LD 5.0 ve SVG şemalarıyla senkronize.");
console.log("======================================================================");
